test: fix MSBuild concurrency
System.InvalidOperationException: The operation cannot be completed because a build is already in progress.

Co-Authored-By: Eva Ditzelmüller <87754804+EvaDitzelmueller@users.noreply.github.com>